[phases.setup]
nixPkgs = ["python3", "postgresql_16", "gcc", "ffmpeg"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput || true",
  "python manage.py migrate || true"
]
